### ISSUE TITLE
It just doesnt work on 10.15 Catalina

### ISSUE THREAD

**Issue by ddohcim** [DaFuqtor/MiddleClick-Catalina#12]
Hi, I followed instructions, installed id via brew, enabled in privacy settings (uninstalled old middleClick app before) and it launches, I can see it in top bar but 3 fingers tap/click just doesnt seems to work. Why? Please help

**Comment by ddohcim** [comment]
and I noticed the app restarts itself every ~15 seconds (the icon disappears and apears again in top bar)

**Comment by DaFuqtor** [comment]
Guys, my ass hurts now :) Read the README...

go to System Preferences > Security & Privacy > Privacy > Accessibility, then Click the lock to make changes and tick MiddleClick under Allow the apps below to control your computer.

Duplicate of #2

**Comment by japgun** [comment]
> and I noticed the app restarts itself every ~15 seconds (the icon disappears and apears again in top bar)

Had same issue. Solved it by:
  1. "brew cask reinstall midclick"
  2. Remove and re-add MiddleClick at privacy > accessibility. 

Any luck?

**Comment by hacker1024** [comment]
Can we close this?

**Comment by ddohcim** [comment]
> Can we close this?

yes, thanks
