### ISSUE TITLE
“MiddleClick.app” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by eyalfa** [DaFuqtor/MiddleClick-Catalina#16]
seems like the app is not signed (or whatever it is that ticks macos...)

**Comment by DaFuqtor** [comment]
Just click on the app icon holding Control, then choose "Open" and the system will allow you to actually open it.

(yes, I don't want to pay $100 to Apple just for cutting our way to open the app for the first time by one little step)

**Comment by eyalfa** [comment]
I'll give it a try, but I'm rather skeptic as my laptop is employer issued pre configured with some security features I can't relax.

**Comment by dmd** [comment]
If that doesn't work, go to the Security and Privacy control panel - there will be a notice IN THAT PANEL asking you to open-anyway.
