### ISSUE TITLE
System-wide · close tabs by middleclicking on them also closes tabs in Safari

### ISSUE THREAD

**Issue by cdf-eagles** [DaFuqtor/MiddleClick-Catalina#18]
Is there any way to disable the System-wide feature for closing tabs? I find that occasionally it will  trigger while I am in Safari (or Chrome, or Firefox) when I want to open a new link and instead it closes the tab I am on.

**Comment by DaFuqtor** [comment]
The function of closing tabs by middleclicking does not work on the entire space of the application, but only on the tabs area.
