### ISSUE TITLE
[Catalina] Doesn't work. Keeps closing and reopening.

### ISSUE THREAD

**Issue by brianmoyano** [DaFuqtor/MiddleClick-Catalina#2]
Hi, until today i was using the old version of MiddleClick, until realized after updating to the final version of Catalina, it stops working after the computer goes to sleep.

So i found this new fork. Downloaded it and when i open it it goes to the taskbar, but it doesn't work and the icon disappears and appears, so i guess it is being closed and opened over and over again.

I don't know how to get a crash log or something like that.

I'm using Catalina Version 10.15 (19A583)

**Comment by labikmartin** [comment]
I cannot even run it.
Installed with Brew but
![image](https://user-images.githubusercontent.com/17283724/66456948-592e8080-ea6f-11e9-9918-5bb36780cd2c.png)

**Comment by DaFuqtor** [comment]
@labikmartin, all you have to do is open the `Applications` folder, do <kbd>Ctrl</kbd>+Click on MiddleClick and press `Open` in the dialog box.

**Comment by DaFuqtor** [comment]
@brianmoyano, yes, that's the expected behaviour.
Now go to `System Preferences` > `Security & Privacy` > `Privacy` > `Accessibility`, then `Click the lock to make changes` and tick `MiddleClick` under `Allow the apps below to control your computer`.
Thus, it'll work. And will stop restarting. 

(It needs Accessibility control to interact with Trackpad and Mouse)

**Comment by ekrapfl** [comment]
If anyone else is having this issue, I noticed that for me, the check was already on, but I think it was from a previous version of the app that I had installed (not this fork).  I actually removed that app from the Accessibility settings, then re-added the MiddleClick app, and now it is working fine for me.

**Comment by DaFuqtor** [comment]
Thank you, @ekrapfl. That's what [the attention](//github.com/DaFuqtor/MiddleClick-Catalina#attention-make-sure-to) was about. Think I should put it in some other place in README.

**Comment by ekrapfl** [comment]
Lol, yep, I totally missed that.  RTM 😊
