### ISSUE TITLE
Doesn't work on MacOS Catalina 10.15 (19A583)

### ISSUE THREAD

**Issue by lpiechowiak** [DaFuqtor/MiddleClick-Catalina#4]
Hello. I've just update my Macbook Pro 13"  (Retina, Early 2015).
Middle Click doesn't work at all.
I've downloaded zip file, I've  tried options with brew cask install, I was trying to change number of buttons, switch between click/touch in GUI.
If you have any questions - feel free to contact.

P.S. I've just notice that MiddleClick icon disappear from time to time so probably is crashing.
P.S.2 Of course before testing I've used "spctl --master-disabled"

**Comment by SilvM** [comment]
I can confirm it's working fine for me on Catalina. I made sure to remove the previous build of Middleclick I had (which was working, but also crashing when my laptop would wake).

I haven't ran spctl tho

**Comment by DaFuqtor** [comment]
From your first P.S., I can see that it's a **duplicate** of #2 and #3. 
It's strange that you know how to use `spctl`, but forgot to **read the documentation**. Just follow the steps listed in [this attention](//github.com/DaFuqtor/MiddleClick-Catalina#attention-make-sure-to).

> Why did I do it so that everyone now feels like the app is crashing? Well, in old versions, it was just crashing and that's all.
This version lets you update from old fork a bit faster if yOu FoLlOw ThE dOcUmEnTaTiOn. It reopens every 5 seconds so after following the steps listed in the attention you don't need to open it manually.

**Comment by lpiechowiak** [comment]
It's strange that you know who read and who not this couple of obvious lines that you called "documentation". ;)
I've read the documentation, added to autostart and make any of described actions. I'll try again when I'll back from work.
Best regards and have a nice day.
