### ISSUE TITLE
Menu bar icon gets messed up when changing between light and dark mode

### ISSUE THREAD

**Issue by shikhanshu** [DaFuqtor/MiddleClick-Catalina#7]
The title of the issue is self explanatory. Here are screenshots.

Normal icon in light mode:
![image](https://user-images.githubusercontent.com/31578/67114084-f3897500-f18f-11e9-831a-68a35befb004.png)

Becomes wonky when switching to dark mode:
![image](https://user-images.githubusercontent.com/31578/67114108-01d79100-f190-11e9-8373-cc612228423a.png)

Same thing happens when switching from dark to light mode.

Quitting and re-opening MiddleClick fixes it.

**Comment by shikhanshu** [comment]
Any ETA on when this will be fixed? It's pretty annoying. I like to use "Auto" mode and have to restart MiddleClick at least twice a day.

**Comment by varentsov** [comment]
I'm also affected
